### ISSUE TITLE
Dashboard in container

### ISSUE THREAD

**Issue by StykMartin** [beaker-project/dandelion#40]
So let's discuss how we should create beaker-dashboard in a container.
In my opinion:

- We will do a multi-stage build. At this point, I believe we will need 2 stages at least.
- 1. Stage - "Build" container where we will put all tooling to make create all static files
- 2. Stage - "Runtime" container. Lightway container for static content + config maps and whatever we need to run it. 

Build container can be heavy, we will discard it anyway. No need to taking care that much about layers and so on. However, in the second one we should run NGINX / APACHE and that's it.

All static data should be copied from 1. Stage to 2.

**Comment by renanrodrigo** [comment]
Agreed. How should we automate the process from stage 1 to stage 2?
Building both is pretty much straightforward: Stage 1 will need only git, npm and magic, while Stage 2 can be any webserver container given static content will be ready.

**Comment by StykMartin** [comment]
We can leverage this bad boy.
https://docs.docker.com/develop/develop-images/multistage-build/#use-multi-stage-builds
